---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oakfoxco/public_html/
    - /usr/bin/rsync -av --exclude='.git' --exclude='.gitignore' --exclude='.cpanel.yml' --exclude='dashboard/.htpasswd' . $DEPLOYPATH
